[package]
name = "renderama"
version = "0.1.0"
authors = ["mandeep <mandeep@users.noreply.github.com>"]

[dependencies]
image = "0.20.0"
nalgebra = "0.15.3"
rand = "0.5.5"
rayon = "1.0.1"

[profile.dev]
opt-level = 2
debug = true
