[package]
name = "renderama"
version = "0.18.0"
authors = ["mandeep <mandeep@users.noreply.github.com>"]

[features]
denoise = ["oidn"]

[dependencies]
image = { git = "https://github.com/image-rs/image" }
nalgebra = "0.17.3"
rand = "0.7.0"
rand_distr = "0.2.1"
rayon = "1.0.3"
oidn = { version = "0.2.0", optional = true }
chrono = "0.4"

[profile.dev]
opt-level = 3
debug = true
