[package]
name = "renderama"
version = "0.12.0"
authors = ["mandeep <mandeep@users.noreply.github.com>"]

[dependencies]
image = "0.21.0"
nalgebra = "0.17.3"
rand = "0.5.5"
rayon = "1.0.3"

[profile.dev]
opt-level = 2
debug = true
