[package]
name = "renderama"
version = "0.24.0"
authors = ["mandeep <mandeep@users.noreply.github.com>"]
edition = "2015"
build = "build.rs"

[features]
denoise = ["oidn"]

[dependencies]
chrono = "0.4.10"
glam = "0.32.1"
image = { version = "0.25", features = ["exr"] }
# image2 = "0.11.3"
nalgebra = "0.19.0"
oidn = { version = "2.3.3", optional = true }
pbr = "1.0.2"
rand = "0.7.2"
rand_distr = "0.2.2"
rayon = "1.2.1"
tobj = "4.0.3"

[profile.dev]
opt-level = 3
debug = true